apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: example-appsodyapplication
spec:
  # Add fields here
  applicationImage: openliberty/open-liberty:javaee8-ubi-min
  service:
    type: ClusterIP
    port: 9080
  expose: true
  autoscaling:
    minReplicas: 2 
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50